<a href="https://colab.research.google.com/github/Alexandre77777/data_mining/blob/main/1.%20%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0/1.%20%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [3]:
import numpy as np
print(np.__version__)

1.26.0


2) Создать нулевой вектор размера 10

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [11]:
np.full((7), 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [259]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [261]:
np.random.random(9)[::-1]

array([0.77608046, 0.14429398, 0.29897202, 0.74800205, 0.48365124,
       0.51770586, 0.79508511, 0.00232163, 0.74642337])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [250]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [246]:
np.eye(4, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [49]:
arr = np.full((16), 7)
arr[::5] = range(4)

arr.reshape((4,4))

array([[0, 7, 7, 7],
       [7, 1, 7, 7],
       [7, 7, 2, 7],
       [7, 7, 7, 3]])

9) Создать матрицу размера 5 на 5 заполненную чиcлами от 0 до 4 в строках.

In [226]:
np.full((5, 5), range(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [228]:
matr = np.random.random((10, 10))

for i in range(matr.shape[0]):
    matr[i] -= np.average(matr[i])

matr

array([[-0.37798352,  0.30513856,  0.28432782, -0.30077411, -0.30762185,
         0.45096924,  0.36777176, -0.43976696,  0.26614833, -0.24820926],
       [ 0.27841339,  0.39998967, -0.37191495,  0.30928263, -0.31918208,
        -0.16340646,  0.06665692,  0.00246294, -0.54405401,  0.34175195],
       [ 0.3422508 ,  0.35887288, -0.1889325 ,  0.45559126, -0.16047175,
        -0.24648679, -0.37815507,  0.00967758, -0.11754264, -0.07480379],
       [ 0.05477756,  0.55992504,  0.33577808, -0.30311997, -0.31872422,
         0.19372456,  0.19436973, -0.24882951, -0.21784893, -0.25005233],
       [-0.23908661, -0.14356794,  0.29468796, -0.4022714 , -0.11047584,
        -0.22809019,  0.46989634,  0.53655848,  0.19663694, -0.37428772],
       [ 0.17557212, -0.24921432,  0.05138151, -0.01169862, -0.27496748,
        -0.29623405, -0.01630873,  0.31588716,  0.23460141,  0.070981  ],
       [ 0.53139667,  0.3878137 , -0.31583718,  0.25142527,  0.16552674,
        -0.02338898, -0.12327752, -0.18492639

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [225]:
matr = np.random.random((10, 10))
for i in range(matr.shape[0]):
    matr[...,i] -= np.median(matr[...,i])

matr

array([[-1.73546082e-01, -5.67388186e-03, -2.95130594e-01,
        -2.14626036e-01, -8.24623834e-03, -2.93402718e-01,
        -2.96210762e-01,  1.27770523e-01, -4.69249916e-01,
         1.20844522e-01],
       [ 6.69119150e-02, -1.60812119e-01, -2.29076718e-01,
         2.28574711e-01,  1.65943958e-01, -3.12700989e-01,
         7.27281656e-02,  3.50730826e-01,  3.20404802e-01,
        -2.67866689e-01],
       [-6.15938645e-01,  1.58085028e-01, -4.37192131e-02,
        -4.49646836e-01, -7.18040790e-02, -8.10395834e-02,
         2.38520127e-01,  2.99082230e-01,  2.76183309e-01,
        -2.70037996e-01],
       [-8.51149713e-03, -1.49228778e-01,  3.16724154e-01,
        -4.34688156e-01,  8.24623834e-03, -1.08654927e-01,
        -1.03756677e-01,  2.78626724e-02, -1.68958770e-02,
        -1.73025276e-01],
       [ 8.51149713e-03, -2.34909481e-01, -3.95106265e-01,
        -3.93014528e-04, -1.16962575e-01, -7.01400217e-02,
         2.70555002e-02, -2.78626724e-02, -3.02586542e-01,
         1.

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [281]:
matr = np.arange(25).reshape((5, 5))
np.vstack([matr, np.min(matr, axis=1), np.max(matr, axis=1)])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  5, 10, 15, 20],
       [ 4,  9, 14, 19, 24]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу чётного произведения.  

In [315]:
vec = np.arange(1, 51)

odd_vec = vec[vec % 2 != 0].reshape((5, 5))
print(f'Non-even vector:\n{odd_vec}\n')

even_vec = vec[vec % 2 == 0].reshape((5, 5))
print(f'Even vector:\n{even_vec}\n')

mult_vec = even_vec.dot(odd_vec)
print(f'Multuplication of\n{mult_vec}\n')

print('Inverse matrix: ')
try:
    print(np.linalg.inv(mult_vec))
except np.linalg.LinAlgError:
    print(None)

Non-even vector:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

Even vector:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

Multuplication of
[[ 830  890  950 1010 1070]
 [1880 2040 2200 2360 2520]
 [2930 3190 3450 3710 3970]
 [3980 4340 4700 5060 5420]
 [5030 5490 5950 6410 6870]]

Inverse matrix: 
None


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [287]:
matr = np.zeros((8, 8))

matr[1::2, ::2] = 1
matr[::2, 1::2] = 1

matr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])